package network;


public enum RequestType {
    LOGIN, LOGOUT, GET_SELLER_BY_EMAIL, GET_SHOWS_BY_DAY, GET_ALL_ARTISTS, GET_SHOWS_BY_ARTIST_ID, GET_ARTIST_BY_ID, GET_SHOW_BY_DATE_AND_PLACE, UPDATE_SHOW
}